version: '3.8'

services:
  emqx:
    image: emqx/emqx:5.8
    container_name: camera_rtsp_emqx
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "18083:18083"
      - "8883:8883"
    environment:
      - EMQX_NODE_NAME=emqx@127.0.0.1
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=galgo2526
      - EMQX_ALLOW_ANONYMOUS=true
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    networks:
      - default

volumes:
  emqx_data:
  emqx_log:
